services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    image: occuevroute-backend
    ports:
      - "9000:8000"
    volumes:
      - ./data:/app/data:ro
      - ./models:/app/models:ro
      - ./ML/Data:/app/ML/Data:ro

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: occuevroute-frontend
    depends_on:
      - backend
    ports:
      - "9090:80"
